### ISSUE TITLE
Please add `ArtifactSource` template type

### ISSUE THREAD

**Issue by ecs-jnguyen** [harness-community/terraform-harness-content#5]
Hi the template `type` variable is validating against a pre defined set of template types. In the harness console you can create an `ArtifactSource` template type. I want to add `ArtifactSource` as an option for template type.

https://github.com/harness-community/terraform-harness-content/blob/main/modules/templates/variables.tf#L97-L110

**Comment by goodrum-harness** [comment]
@ecs-jnguyen , Thank you for the enhancement request.  We included this as part of a new update we released today
https://github.com/harness-community/terraform-harness-content/releases/tag/v0.4.0
